apiVersion: v1
kind: ConfigMap
metadata: 
  name: redis-cm
  namespace: redis-cluster
data: 
  redis.conf: |-
    appendonly yes
    maxmemory 5mb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-standalone
  namespace: redis-cluster
spec:
  serviceName: redis-standalone
  replicas: 1
  selector:
    matchLabels:
      app: redis-standalone
  template:
    metadata:
      labels:
        app: redis-standalone
    spec:
      containers:
      - name: redis-standalone
        image: redis
        command: ["redis-server"]
        args: ["/usr/local/etc/redis/redis.conf"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 6379
        volumeMounts:
          - name: standalone-pv 
            mountPath: /data
          - name: config
            mountPath: /usr/local/etc/redis
      volumes:
        - name: config
          configMap: 
            name: redis-cm
  volumeClaimTemplates:
    - metadata:  
        name: standalone-pv 
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
