apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: use-secret
  namespace: k8s-yaml
spec: 
  replicas: 1
  selector: 
    matchLabels: 
        app: busybox
  template: 
    metadata: 
      labels: 
        app: busybox
    spec: 
      containers: 
        - name: list-files
          image: busybox
          command: ["sh", "-c", "ls /data"]
          volumeMounts: 
            - name: data
              mountPath: /data
        - name: show-file
          image: busybox
          # 注意路径
          command: ["sh", "-c", "cat /data/test/passwd && echo '1' || echo '0'"]
          volumeMounts: 
            - name: data02
              mountPath: /data
      volumes:
        - name: data
          secret: 
            secretName: secret
        - name: data02
          secret: 
            secretName: secret
            # 自定义卷挂载的路径
            items: 
              - key: password
                path: test/passwd
          