apiVersion: batch/v1
kind: Job
metadata: 
  name: test-job
  namespace: k8s-yaml
spec: 
  # 需要完成次数
  completions: 10
  # 并行数
  parallelism: 2
  template: 
    metadata: 
      name: test-job
    spec: 
      containers: 
        - name: test-job
          image: busybox
          command: ["sh", "-c", "echo 'hahahahhahahah'"]
      restartPolicy: Never
      