apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-rc
  namespace: k8s-yaml
spec: 
  replicas: 3
  selector:
    app: nginx 
  templates: 
    metadata: 
      name: nginx 
      labels: 
        app: nginx 
    spec: 
      containers: 
        - name: nginx
          image: nginx
          ports: 
            - name: nginx-port
              containerPort: 80
              