apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv01
  namespace: k8s-yaml
spec: 
  capacity: 
    storage: 10M 
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /tmp/data
  