apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc01
  namespace: k8s-yaml
spec:   
  accessModes: 
    - ReadWriteOnce
  resources:
    requests: 
      storage: 10M 
      