apiVersion: v1
kind: Namespace
metadata:
  name: kube-prometheus
  labels:
    name: kube-prometheus

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    # 配合 Ingress-nginx
    - job_name: 'ingress-nginx'
      static_configs:
      - targets: ['ingress-prome-svc.ingress-nginx.svc.cluster.local:10254']
