apiVersion: v1
kind: ConfigMap
metadata: 
  name: nginx-fluent-cm
  namespace: efk
data: 
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers
    </system>
  
  nginx.input.conf: |-
    <source>
      @id nginx.log
      @type tail
      path /var/log/nginx/*.log
      pos_file /var/log/nginx/nginx.log.pos
      tag nginx
      read_from_head true
      <parse>
        @type nginx
      </parse>
    </source>

    <filter nginx>
      @type record_transformer
      <record>
		# 添加一个 k8s.name 的字段
        k8s.name "nginx"
        tag ${tag}
      </record>
    </filter>
  
  output.conf: |-
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      type_name _doc
      include_tag_key true
      host efk-svc
      port 9200
      logstash_format true
      <buffer>
        @type file
        path /var/log/nginx/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
