apiVersion: v1
kind: ServiceAccount
metadata: 
  name: fluentd
  namespace: efk

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: fluentd
rules: 
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: fluentd
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: efk
roleRef: 
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
