# production logs
# /var/log/gitlab/gitlab-rails/production.log
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: cicd 
spec:
  serviceName: gitlab-svc
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: |
              postgresql['enable'] = false
              gitlab_rails['db_username'] = "gitlab"
              gitlab_rails['db_password'] = "gitlab"
              gitlab_rails['db_host'] = "pg-svc"
              gitlab_rails['db_port'] = "5432"
              gitlab_rails['db_database'] = "gitlab_prod"
              gitlab_rails['db_adapter'] = 'postgresql'
              gitlab_rails['db_encoding'] = 'utf8'
              redis['enable'] = false
              gitlab_rails['redis_host'] = 'redis-svc'
              gitlab_rails['redis_port'] = '6379'
              gitlab_rails['gitlab_shell_ssh_port'] = 30122
              external_url 'http://35.229.134.236:30180'
        resources:
          requests:
            memory: "1G"
            cpu: "1000m"  
          limits:
            memory: "2Gi"
            cpu: "2000m"
        ports:
        - containerPort: 30180
          name: web-port
        - containerPort: 22
          name: ssh-port
        volumeMounts:
          - name: gitlab-pvc
            mountPath: /var/opt/gitlab
  volumeClaimTemplates:
    - metadata:
        annotations: 
          volume.beta.kubernetes.io/storage-class: managed-nfs-storage
        labels:
          app: gitlab
        name: gitlab-pvc
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests: 
            storage: 50M

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: cicd
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    # 修改，30080 和 Ingress-nginx 冲突
    nodePort: 30180
    name: web
  - port: 22
    targetPort: ssh-port
    nodePort: 30122
    name: ssh
