apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  namespace: cicd 
spec:
  serviceName: gitlab-svc
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce
        env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: |
              postgresql['enable'] = false
              gitlab_rails['db_username'] = "gitlab"
              gitlab_rails['db_password'] = "gitlab"
              gitlab_rails['db_host'] = "pg-svc"
              gitlab_rails['db_port'] = "5432"
              gitlab_rails['db_database'] = "gitlab_prod"
              gitlab_rails['db_adapter'] = 'postgresql'
              gitlab_rails['db_encoding'] = 'utf8'
              redis['enable'] = false
              gitlab_rails['redis_host'] = 'redis-svc'
              gitlab_rails['redis_port'] = '6379'
              gitlab_rails['gitlab_shell_ssh_port'] = 30022
              external_url 'http://35.229.134.236:30080'
        resources:
          requests:
            memory: "500M"
            cpu: "500m"  
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: web-port
        - containerPort: 22
          name: ssh-port

---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
  namespace: cicd
spec:
  selector:
    app: gitlab
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    nodePort: 30080
    name: web
  - port: 22
    targetPort: ssh-port
    nodePort: 30022
    name: ssh
